### PR TITLE
BITMAKER-1946 Roles implementation for estela user permissions

### PR DESCRIPTION
**Pull request by raymond1242**
# Description

Implement a permission system for estela based on Django Roles document : https://docs.google.com/document/d/1Pxd60qPmkNvbrj6Um6wgIeWMtGKKKT8_2mMs5ahQKr8/edit?usp=sharing

# Issue

[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/1946)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines of this project.
- [x] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [x] New and existing tests pass locally with my changes.
- [x] If this change is a core feature, I have added thorough tests.
- [x] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [x] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

### CODE REVIEW

**Comment by raymond1242** [comment]
@rodp63 I think is done

**Comment by raymond1242** [comment]
@Adriana618 I think is done, could you review this PR

**Review by Adriana618 — CHANGES_REQUESTED** [review]
Applied lint please.

**Comment by raymond1242** [comment]
@Adriana618 I add a migrations file for this model's modification

**Review by Adriana618 — APPROVED** [review]
Looks good. But think that in Bitmaker Cloud we already have projects created with old roles, create a ticket to see how to pass this projects to new roles. This was made in the pass with user and permissions, you can see migrations 0011 to 0013 for a example.

**Comment by raymond1242** [comment]
@Adriana618 I already add the migration to change old values

**Pull request merged**
