### PR TITLE
BITMAKER-2102 estela-web: Implement "In Projects/Activity"

### PR DESCRIPTION
**Pull request by reqhiem**
# Description

Implement "In Projects/Activity" mockup

# Issue

https://tasks.bitmaker.dev/issues/2102

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines of this project.
- [x] I have made corresponding changes to the [documentation](https://github.com/bitmakerla/estela/tree/main/docs).
- [x] New and existing tests pass locally with my changes.
- [x] If this change is a core feature, I have added thorough tests.
- [x] If this change affects or depends on the behavior of other _estela_ repositories, I have created pull requests with the relevant changes in the affected repositories. Please, refer to our [official documentation](https://estela.bitmaker.la/docs/).
- [x] I understand that my pull request may be closed if it becomes obvious or I did not perform all of the steps above.

### CODE REVIEW

**Comment by raymond1242** [comment]
@reqhiem this is ready to review?

**Review by raymond1242 — CHANGES_REQUESTED** [review]
Correct she and position of icons

**Comment by raymond1242** [comment]
It's OK, make a rebase and Itl will be approved

**Comment by reqhiem** [comment]
@raymond1242 rebase done

**Review by raymond1242 — APPROVED** [review]
Good Job!

**Comment by raymond1242** [comment]
@reqhiem This PR is ready to merge

**Pull request merged**
